# -*- coding: utf-8 -*-
"""Bancă de întrebări — 19 per pagină, folosite vizibil ȘI în schema FAQPage."""

FAQ = {}

FAQ["/"] = [
("Ce face AiVenture, pe scurt?","Pregătim firma ta pentru felul în care AI-ul o descoperă, o înțelege, o recomandă și, în timp, o poate utiliza. Nu îți construim un chatbot și nu îți refacem site-ul."),
("Ce înseamnă „AI pentru firma ta”?","Înseamnă că punctul de plecare este firma ta, nu tehnologia. Începem de la ce știe AI-ul despre ea azi și mergem pas cu pas mai departe."),
("Cât costă să aflu unde sunt?","Verificarea inițială este gratuită. Plătești doar dacă decizi să repari ce lipsește."),
("Trebuie să știu ce este un LLM ca să lucrez cu voi?","Nu. Tot ce trebuie să înțelegi este dacă AI-ul găsește firma ta, dacă o descrie corect și dacă are motive să o recomande."),
("Cât durează o verificare?","Câteva minute. Primești un raport cu ce găsește AI-ul, ce înțelege greșit și ce lipsește."),
("Ce sisteme AI verificați?","ChatGPT, Gemini, Perplexity și Google AI. Rezultatul este un snapshot la data scanării."),
("De ce contează dacă AI-ul mă înțelege?","Pentru că tot mai mulți clienți nu mai caută, ci întreabă. Dacă AI-ul nu are informație suficientă despre tine, nu ai cum să apari în răspuns."),
("Este același lucru cu SEO?","Nu. SEO optimizează pentru ca oamenii să găsească pagini. Noi lucrăm la ce poate un sistem AI să înțeleagă și să verifice despre firmă."),
("Îmi trebuie SEO în continuare?","Da. SEO rămâne util. Dar nu mai este suficient singur, pentru că mecanismul prin care ajunge clientul la tine s-a schimbat."),
("Trebuie să-mi refac website-ul?","Nu. Stratul AI se adaugă peste site-ul existent, fără să-l reconstruiești."),
("Pe ce platformă trebuie să fie site-ul meu?","Nu contează. Lucrăm cu WordPress, platforme custom, magazine online sau site-uri statice."),
("Ce se întâmplă după verificare?","Îți arătăm exact ce lipsește și care este următoarea treaptă. Nu ești obligat să mergi mai departe."),
("Lucrați și cu firme mici?","Da. Un freelancer sau o firmă de câțiva oameni are aceeași problemă ca o companie mare: dacă AI-ul nu îl cunoaște, nu îl recomandă."),
("Ce este un agent AI?","Un sistem software căruia îi dai un obiectiv și care poate decide singur ce pași să facă. Chatbotul răspunde. Agentul acționează."),
("Am nevoie de un agent acum?","Cel mai probabil nu. Pentru majoritatea firmelor, primul pas este să fie găsite și înțelese corect."),
("Ce este A2A?","Comunicarea directă între agentul unui client și agentul unei firme. Este destinația scării, nu punctul de plecare."),
("Cine este ECBTAX?","Un partener AiVenture — firmă de contabilitate, fiscalitate, HR și finanțe — pe care îl folosim ca demonstrație reală."),
("Sunteți o agenție de marketing?","Nu. Nu facem campanii și nu producem conținut promoțional. Lucrăm la reprezentarea firmei în sistemele AI."),
("De unde încep?","Cu verificarea gratuită. Nu trebuie să înțelegi AI ca să afli unde este firma ta."),
]

FAQ["/niveluri/"] = [
("Ce sunt nivelurile AI?","O scară cu patru trepte: vizibilă, înțeleasă, acționabilă și A2A. Fiecare treaptă răspunde unei întrebări diferite despre firma ta."),
("Cum știu la ce nivel sunt?","Prin verificarea gratuită. Îți arată concret unde te afli, nu doar teoretic."),
("Pot sări direct la nivelul 3?","Tehnic da, practic nu are sens. Un agent peste informație dezordonată devine o interfață peste haos."),
("Nivelul 1 înseamnă că am doar site?","Înseamnă că Google te găsește, dar informația a fost gândită pentru oameni, nu pentru sisteme AI."),
("Ce lipsește tipic la nivelul 1?","Informație structurată despre cine ești, ce faci, pentru cine și unde — într-o formă pe care AI-ul o poate prelua fără să ghicească."),
("Ce înseamnă concret nivelul 2?","AI-ul nu doar știe că exiști, ci poate explica ce faci, pentru cine ești potrivit și de ce."),
("De ce e greu să treci de la 1 la 2?","Pentru că informația despre o firmă este de obicei împrăștiată și uneori contradictorie între surse."),
("Ce înseamnă „verificabil”?","Că afirmațiile despre firmă pot fi confirmate din mai multe surse, nu doar de pe propriul site."),
("Nivelul 3 înseamnă că îmi trebuie API-uri?","Da, într-o formă sau alta. Un agent are nevoie de ceva cu care să interacționeze, nu doar de text."),
("Ce fel de acțiuni poate face un agent?","Poate cere informații, solicita o ofertă, verifica disponibilitatea, programa o discuție sau porni un proces comercial."),
("Pot controla ce face un agent cu firma mea?","Da. Permisiunile, limitele și punctele unde intervine un om se stabilesc explicit."),
("Ce este Human-in-the-Loop?","Un punct în proces unde decizia rămâne la om, chiar dacă restul pașilor sunt automatizați."),
("A2A este disponibil azi?","Parțial. Este direcția clară de evoluție, dar pentru majoritatea firmelor nu este prioritatea imediată."),
("Cât durează urcarea unei trepte?","Depinde de cât de dispersată este informația firmei. Se stabilește după verificare, nu înainte."),
("Pot rămâne la nivelul 2?","Da. Pentru multe firme, nivelul 2 este suficient pentru următorii ani."),
("Nivelurile se pierd în timp?","Se pot degrada, da. Informația se schimbă, site-urile se modifică, sursele se contrazic."),
("Se poate măsura progresul?","Da. Rescanarea arată diferența față de starea inițială."),
("Firma mea poate fi la niveluri diferite pe departamente?","Da, frecvent. Marketingul poate fi la 2 în timp ce restul firmei este la 1."),
("Ce fac dacă sunt deja la nivelul 3?","Discutăm despre A2A și despre menținerea a ceea ce ai construit."),
]

FAQ["/verifica/"] = [
("Ce primesc după verificare?","Un raport despre vizibilitate, acuratețea descrierii, serviciile identificate, informațiile lipsă și pașii prioritari."),
("Verificarea este într-adevăr gratuită?","Da. Diagnosticul inițial nu se plătește."),
("Ce introduc în formular?","Doar domeniul firmei. Nu ai nevoie de cont."),
("Cât durează?","Câteva minute, în funcție de câte sisteme sunt interogate."),
("Ce sisteme AI sunt verificate?","ChatGPT, Gemini, Perplexity și Google AI."),
("Ce înseamnă „nu apar”?","AI-ul nu are nicio informație despre firma ta. Problema este de descoperire."),
("Ce înseamnă „apar greșit”?","AI-ul spune ceva despre firmă, dar incorect: alte servicii, altă regiune, sau confuzie cu o firmă cu nume similar."),
("Ce înseamnă „apar incomplet”?","Informația este corectă, dar insuficientă pentru ca AI-ul să aibă motive să te recomande."),
("Care este cel mai frecvent rezultat?","„Apar incomplet”. Majoritatea firmelor există în AI, dar fără suficient context ca să fie alese."),
("Rezultatul se poate schimba?","Da. Este un snapshot la data scanării. Sistemele AI își actualizează informația."),
("De ce scorurile diferă între sisteme?","Pentru că fiecare sistem are surse și metode de actualizare diferite."),
("Ce fac cu un scor mic?","Îl folosești ca punct de plecare. Un scor mic arată unde e cel mai mult de câștigat."),
("Un scor mare înseamnă că nu am nevoie de nimic?","Nu neapărat. Poți fi bine găsit și totuși prost înțeles."),
("Îmi păstrați datele?","Doar ce este necesar pentru a-ți livra raportul și a răspunde solicitării."),
("Pot verifica un competitor?","Da. Domeniul este public, iar rezultatul reflectă ce spune AI-ul public despre el."),
("Pot rescana mai târziu?","Da, și este recomandat după orice modificare importantă."),
("Verificarea îmi schimbă site-ul?","Nu. Este strict o citire, nu o modificare."),
("Sunt obligat să cumpăr ceva după?","Nu. Raportul este al tău."),
("Ce urmează după raport?","Dacă vrei, trecem la audit și la remedierea a ceea ce lipsește."),
]

FAQ["/eu-ai-act-ready/"] = [
("Ce este EU AI Act Ready?","Produsul nostru de intrare în zona de conformitate: pregătirea documentară și organizațională a firmei pentru cerințele Regulamentului european privind AI."),
("Firma mea intră sub incidența regulamentului?","Depinde de cum folosești AI și în ce rol — furnizor sau utilizator. Punctul de plecare este un inventar al sistemelor AI folosite în firmă."),
("Folosesc doar ChatGPT ocazional. Mă privește?","Posibil. Utilizarea unui sistem AI în activitatea firmei poate atrage obligații, chiar dacă nu ai dezvoltat tu sistemul."),
("Ce înseamnă „ready” și ce nu înseamnă?","Înseamnă că sprijinim pregătirea. Nu certificăm conformitatea și nu înlocuim o evaluare juridică."),
("Îmi dați un certificat?","Nu. Producem documentație și structură care susțin pregătirea, nu un certificat de conformitate."),
("Care este primul pas?","Inventarul sistemelor AI folosite în firmă și clasificarea lor pe niveluri de risc."),
("De ce am nevoie de un inventar?","Pentru că nu poți documenta sau controla ceva ce nu știi că se folosește în firmă."),
("Cine ar trebui să se ocupe intern?","De obicei o persoană din conducere, sprijinită de IT și, unde există, de responsabilul cu protecția datelor."),
("Are legătură cu GDPR?","Se suprapun parțial, dar sunt lucruri diferite: unul privește datele personale, celălalt sistemul AI și riscul lui."),
("Documentația mea GDPR e suficientă?","De regulă nu. Acoperă alt obiect și nu răspunde acelorași întrebări."),
("Ce documente rezultă?","Inventar, clasificare, documentație de furnizor, proceduri de supraveghere umană și materiale de transparență."),
("Cât durează?","Depinde de câte sisteme AI folosești și cât de documentate sunt deja. Se stabilește după inventar."),
("Ce este AI literacy?","Nivelul de înțelegere pe care oamenii din firmă trebuie să îl aibă despre sistemele AI cu care lucrează."),
("Trebuie să fac training intern?","Da, într-o formă proporțională cu felul în care firma folosește AI."),
("Ce înseamnă supraveghere umană?","Că există puncte clare în care un om verifică sau poate opri ce face sistemul AI."),
("Am nevoie de jurnal de acțiuni?","Pentru anumite utilizări, da. Un jurnal arată ce s-a întâmplat, când și la inițiativa cui."),
("Legătura cu restul serviciilor AiVenture?","Conformitatea privește cum folosești AI intern. Restul scării privește cum te vede AI-ul din exterior. Sunt complementare."),
("Unde găsesc textul legal și termenele?","Pe site-ul nostru dedicat conformității, unde informația este verificată sursă cu sursă și actualizată separat."),
("De unde încep concret?","Cu o discuție de calificare: ce sisteme AI folosești, în ce rol și pentru ce decizii."),
]

FAQ["/exemplu-ecbtax/"] = [
("De ce ECBTAX?","Pentru că este un business concret, cu servicii clare, exact genul de firmă pe care un client o caută întrebând AI-ul."),
("Este un client sau un partener?","Partener AiVenture. Parteneriatul este public pe ecbtax.com."),
("Ce face ECBTAX?","Contabilitate, fiscalitate, HR și servicii financiare pentru companii și antreprenori."),
("Ce demonstrează exemplul?","Ce știe și ce nu știe AI-ul despre o firmă reală — înainte de orice intervenție."),
("De ce nu un case study clasic?","Pentru că un case study se citește, iar o demonstrație se urmărește. Vrem să vezi problema, nu să ți-o descriem."),
("Informația despre ECBTAX era greșită?","Nu neapărat greșită. Problema tipică este că este dispersată și insuficient de explicită pentru un sistem AI."),
("Ce lipsea concret?","Elementele de diferențiere și dovezile — exact ce îi trebuie AI-ului ca să aibă motive să recomande, nu doar să menționeze."),
("Ați inventat informație nouă?","Nu. Facem informația existentă mai ușor de găsit și de înțeles. Nu adăugăm afirmații care nu sunt reale."),
("Cum arată diferența?","Prin comparație: ce răspundea AI-ul înainte și ce poate răspunde după ce informația este structurată."),
("Se poate reproduce pentru firma mea?","Da. Același proces se aplică oricărei firme cu servicii și clienți definiți."),
("Contează domeniul de activitate?","Contează cât de clar poți descrie ce faci și pentru cine. Contabilitatea este un exemplu bun tocmai pentru că e specifică."),
("Cât a durat?","Durata depinde de cât de dispersată este informația inițială."),
("Este nevoie de acces la site?","Pentru intervenție, da. Pentru diagnostic, nu — se face din exterior."),
("Ce sisteme AI ați interogat?","ChatGPT, Gemini, Perplexity și Google AI."),
("Rezultatul rămâne valabil?","Este un snapshot. Se recomandă rescanarea periodică."),
("Pot vedea raportul complet?","Raportul detaliat se discută direct, nu se publică integral."),
("De ce publicați ce nu știa AI-ul?","Pentru că problema este comună aproape tuturor firmelor. Nu este un defect al ECBTAX."),
("Aveți și alte exemple?","ECBTAX este primul exemplu public. Altele urmează în aceeași structură."),
("Cum încep pentru firma mea?","Cu verificarea gratuită — același prim pas."),
]

FAQ["/cum/"] = [
("Ce este JSON, pe scurt?","Un format prin care informația se scrie în câmpuri clare, fără ambiguitate. Un om citește o propoziție; o mașină citește câmpuri separate."),
("Chiar nu se vede pe site?","Nu. Stratul pentru mașini stă într-un loc al paginii pe care browserul nu îl afișează. Vizitatorul vede exact același site."),
("Se schimbă ceva în design?","Nimic. Nici text, nici imagini, nici butoane, nici viteza de încărcare."),
("Este ceva ascuns sau necinstit?","Nu. Informația pentru mașini trebuie să spună exact același lucru ca cea pentru oameni. Dacă diferă, sistemele o penalizează."),
("De ce nu citesc mașinile direct textul de pe pagină?","Îl citesc, dar trebuie să ghicească ce înseamnă. Un preț scris în text poate fi confundat cu o dată sau un cod. Într-un câmp numit „preț”, nu."),
("Este același lucru cu meta tag-urile vechi?","Nu. Meta tag-urile descriau pagina. Aici descrii firma: cine e, ce face, pentru cine, în ce condiții."),
("Google folosea deja așa ceva?","Da, de ani buni, pentru rezultate îmbogățite. Ce e nou este că acum și sistemele AI conversaționale citesc acest strat."),
("JSON face AI-ul inteligent?","Nu. Îi dă doar un mod structurat de a primi informația. Inteligența vine din date plus reguli plus software care interpretează și decide."),
("Cum „știe” un model despre firma mea?","De obicei nu știe din memorie. Ori găsește informația când caută, ori o aproximează. Când aproximează, greșește fără să știe că greșește."),
("De ce se spune „autocomplete probabilistic”?","Pentru că modelul nu scoate texte dintr-o arhivă. A învățat tipare și calculează ce urmează, bucată cu bucată. Metafora e utilă, deși simplifică."),
("Ce se întâmplă dacă nu am acest strat?","Site-ul rămâne perfect funcțional pentru oameni. Doar că mașinile trebuie să deducă totul din text, iar deducerea greșită e frecventă."),
("Orice site poate primi stratul?","Da. Nu contează platforma — WordPress, magazin online, site custom sau pagini statice."),
("Cât durează adăugarea?","Depinde de cât de clară este informația de la care pornim. Partea tehnică e rapidă; partea grea e să stabilim ce e adevărat și cum se spune."),
("Se poate scoate dacă nu-mi place?","Da. Stratul este separat de site, deci poate fi dezactivat fără urme."),
("Afectează viteza site-ului?","Nu semnificativ. Sunt câțiva kilobytes de text, livrați odată cu pagina."),
("Cine decide ce scrie acolo?","Tu. Noi structurăm ce ne spui și verificăm consecvența. Nu inventăm informație despre firma ta."),
("Ce se întâmplă dacă informația se schimbă?","Se actualizează stratul. De aceea trăiește separat de conținut — ca să poată fi schimbat fără să atingi site-ul."),
("Mașinile chiar comunică între ele fără om?","Da, și o fac de mult timp pentru lucruri simple. Ce e nou este că pot schimba întrebări și intenții, nu doar fișiere."),
("De unde încep?","Cu verificarea gratuită: îți arată ce citesc azi mașinile despre firma ta."),
]


FAQ["/cum/descoperire/"] = [
("Ce înseamnă că Google „mă găsește”?","Că motorul a ajuns pe paginile tale, le-a citit și le păstrează într-un index din care le poate scoate când cineva caută ceva potrivit."),
("Dacă am site, sunt automat găsit?","Nu neapărat. Un site poate exista fără să fie citit sau fără să fie considerat relevant pentru vreo întrebare."),
("Ce împiedică cel mai des descoperirea?","Reguli de acces care blochează motoarele, pagini care se încarcă doar prin script, sau lipsa unei hărți a site-ului."),
("Ce este un crawler?","Un program care parcurge paginile web și le citește conținutul. Google are unul, sistemele AI au altele."),
("Crawlerele AI sunt aceleași cu ale Google?","Nu. Sunt programe separate, cu reguli separate. Poți fi accesibil pentru unul și blocat pentru altul, fără să știi."),
("Cum știu cine îmi citește site-ul?","Din jurnalele serverului sau printr-o analiză dedicată. De obicei rezultatul surprinde: unele crawlere aduc valoare, altele doar consumă."),
("Pot alege cine intră?","Da. Regulile de acces se stabilesc pe categorii de vizitatori automați. Nu toate merită tratate la fel."),
("Ce este harta site-ului?","Un fișier care listează paginile importante, ca motoarele să nu depindă de noroc ca să le găsească."),
("Google Business Profile mai contează?","Da, pentru firmele cu prezență locală. Controlează cum apari în Search și Maps."),
("Descoperirea garantează vizibilitatea?","Nu. Sunt lucruri diferite: a fi citit nu înseamnă a fi arătat cuiva."),
("Cât durează până sunt găsit?","De la ore la săptămâni, în funcție de vechimea domeniului și de câte alte site-uri trimit către tine."),
("Un site nou pornește dezavantajat?","Da, dar temporar. Lipsa istoricului se compensează cu claritate și consecvență."),
("Contează viteza site-ului?","Da, indirect. Un site lent este parcurs mai rar și mai superficial."),
("Ce fac dacă apar pagini vechi în rezultate?","Se semnalează ce s-a schimbat. Indexul nu se actualizează instant."),
("Descoperirea ține de SEO?","În mare parte, da. Este partea în care SEO clasic rămâne pe deplin valabil."),
("Deci SEO nu a murit?","Nu. Rezolvă însă doar prima parte a lanțului. Restul etapelor cer altceva."),
("Ce verificați concret?","Dacă ești accesibil, ce anume poate fi citit, cine te citește efectiv și ce nu ajunge niciodată să fie parcurs."),
("Se poate repara repede?","Partea de acces, de obicei da. Este cel mai ieftin pas din tot lanțul."),
("De unde încep?","Cu verificarea gratuită — arată dacă problema e la descoperire sau mai departe."),
]

FAQ["/cum/intelegere/"] = [
("Ce înseamnă că AI-ul „mă înțelege”?","Că poate spune corect ce faci, pentru cine, unde și în ce condiții — nu doar că îți știe numele."),
("De ce mă descrie greșit?","Pentru că deduce din text. Când textul e ambiguu sau împrăștiat, deducția o ia într-o direcție greșită."),
("Mă confundă cu altă firmă. De ce?","Nume asemănătoare, domenii apropiate sau informație insuficientă ca să vă separe clar."),
("Ce este o entitate?","Firma ta ca lucru distinct, nu ca șir de cuvinte. O entitate clară nu se confundă cu alta."),
("De ce contează consecvența între surse?","Pentru că informația contradictorie nu se ignoră — scade încrederea în toate variantele deodată."),
("Ce dovezi caută un sistem AI?","Confirmări din surse independente: alte site-uri, registre publice, mențiuni verificabile."),
("Pot să-mi scriu singur descrierea?","Da, și e chiar de preferat. Noi o structurăm și verificăm dacă se susține."),
("Dacă scriu mai mult, mă înțelege mai bine?","Nu. Volumul nu ajută. Claritatea, da."),
("Diferența față de descoperire?","La descoperire întrebarea e „ajunge la mine?”. Aici e „a înțeles corect ce a găsit?”."),
("Cum verific ce înțelege despre mine?","Îl întrebi direct, în mai multe sisteme, cu formulări diferite. Diferențele dintre răspunsuri arată unde e problema."),
("De ce răspunde diferit de fiecare dată?","Pentru că generează probabilistic. Când informația e solidă, variația scade mult."),
("Ce se întâmplă dacă informația mea se schimbă?","Sistemele se actualizează în ritmul lor. Un strat structurat scurtează acest timp."),
("Contează recenziile?","Contează ca semnal de credibilitate, dar nu înlocuiesc o descriere clară a ce faci."),
("E același lucru cu schema.org?","Schema.org e unul dintre instrumente. Înțelegerea depinde de ce declari, nu doar de formatul folosit."),
("Pot corecta o informație greșită?","Poți corecta sursa și face varianta corectă mai clară și mai bine susținută. Nu poți edita direct memoria unui model."),
("Cât durează până se corectează?","Săptămâni, de obicei. Depinde de cât de des este recitită sursa."),
("Ce e cel mai des lipsă?","Publicul țintă și condițiile: pentru cine ești potrivit și pentru cine nu."),
("De ce contează „pentru cine nu”?","Pentru că un sistem care știe când nu ești potrivit te recomandă mai încrezător când ești."),
("De unde încep?","Cu verificarea gratuită — îți arată exact ce înțelege greșit."),
]

FAQ["/cum/actiune/"] = [
("Ce înseamnă că un agent „acționează”?","Că nu doar răspunde despre tine, ci poate face un pas concret: cere o ofertă, verifică disponibilitatea, trimite o solicitare."),
("Care e diferența față de un chatbot?","Chatbotul răspunde. Agentul primește un obiectiv, decide pașii și folosește instrumente ca să-l atingă."),
("Îmi trebuie un chatbot pe site?","Nu. Sunt lucruri diferite. Un chatbot vorbește cu oamenii; aici e vorba de ce poate face un program în numele lor."),
("Ce trebuie expus concret?","Ce servicii ai, în ce condiții, cu ce disponibilitate și ce se poate cere — într-o formă apelabilă, nu doar descrisă."),
("Îmi trebuie API?","Într-o formă sau alta, da. Un agent are nevoie de ceva de apelat, nu doar de text de citit."),
("Nu am sisteme interne. Se poate?","Da, la un nivel simplu: preluarea unei cereri structurate e util chiar și fără integrare completă."),
("Pierd controlul asupra firmei?","Nu. Tu stabilești ce se poate cere, ce se poate afla și unde se oprește automatizarea."),
("Ce este human-in-the-loop?","Un punct în proces unde decizia rămâne la un om, chiar dacă restul pașilor sunt automați."),
("Un agent poate semna în numele meu?","Nu, dacă nu i-ai dat explicit acest drept. Permisiunile sunt granulare și implicit restrictive."),
("Cum știu cine a făcut ce?","Prin jurnal de acțiuni: ce s-a cerut, când, de către cine și ce s-a răspuns."),
("Ce riscuri există?","Cereri automate în volum, sau agenți care cer informație pe care nu vrei să o expui. Ambele se limitează din permisiuni."),
("Pot limita cine are acces?","Da. Nu orice agent trebuie tratat la fel, exact ca la crawlere."),
("Ce câștig concret?","Cereri primite și calificate fără operator, inclusiv în afara programului."),
("Riscă să înlocuiască oamenii din firmă?","În practică preia pașii repetitivi de la început. Decizia și relația rămân la oameni."),
("Cât de aproape e asta?","Există deja și funcționează. Nu e majoritar încă — de aceea e fereastra de avantaj."),
("Merită dacă am firmă mică?","Depinde. Dacă primești multe cereri similare, da. Dacă nu, mai întâi etapele anterioare."),
("Trebuie să trec prin etapele anterioare?","Da. Un agent peste informație dezordonată devine o interfață peste haos."),
("Ce se strică dacă sar peste ele?","Agentul răspunde cu încredere lucruri greșite — mai rău decât să nu răspundă deloc."),
("De unde încep?","Cu verificarea: dacă ești deja înțeles corect, această etapă devine următorul pas logic."),
]

FAQ["/cum/a2a/"] = [
("Ce înseamnă A2A?","Agent-to-Agent: agentul unui client comunică direct cu agentul unei firme, fără ca omul să intermedieze fiecare pas."),
("Chiar se întâmplă deja?","Există standarde și implementări. Nu este încă un comportament de masă — de aceea e o direcție, nu o urgență."),
("De ce nu e produsul de intrare?","Pentru că presupune toate etapele anterioare rezolvate. Este destinația scării, nu prima treaptă."),
("Cum se găsesc agenții între ei?","Printr-o descriere publicată a capabilităților: ce știe să facă un agent și pe unde poate fi apelat."),
("Ce e o carte de identitate de agent?","Un fișier care declară numele, capabilitățile și punctul de acces al agentului. Așa devine descoperibil."),
("Agenții negociază preț?","Pot compara condiții. Cât din negociere este permisă este decizia ta, nu a lor."),
("Cine răspunde dacă un agent greșește?","Firma rămâne responsabilă pentru ce expune. De aceea permisiunile și jurnalul contează mai mult decât viteza."),
("Se poate verifica cine a cerut ceva?","Da, prin identitate de agent și jurnal. Fără ele, nu ai cum să reconstitui ce s-a întâmplat."),
("Ce e diferit față de etapa anterioară?","Acolo un agent lucra cu firma ta. Aici doi agenți lucrează între ei, iar tu stabilești limitele."),
("Rămâne omul în proces?","Pentru deciziile care contează, da. Nimic nu obligă la automatizare completă."),
("Ce firme au nevoie primele?","Cele cu cereri repetitive, standardizabile: servicii recurente, disponibilitate, ofertare pe criterii clare."),
("Dacă nu intru acum, pierd?","Nu imediat. Dar cine intră devreme învață pe volum mic, iar ceilalți învață pe volum mare."),
("Este un standard stabilizat?","Se maturizează. De aceea construim ca schimbarea de protocol să nu ceară refacerea a tot."),
("Îmi trebuie infrastructură nouă?","Nu neapărat. Interfața agentului stă peste sistemele existente."),
("Cât costă?","Se stabilește după ce știm ce expui și ce sisteme ai. Este nivelul cel mai variabil."),
("Se poate opri?","Da. Un agent expus poate fi retras oricând, spre deosebire de informație publicată."),
("Ce se întâmplă cu site-ul meu?","Rămâne. Oamenii continuă să îl folosească. A2A este un canal în plus, nu un înlocuitor."),
("Cine decide ce poate cere un agent extern?","Tu, prin permisiuni explicite. Implicit nu se poate nimic."),
("De unde încep, realist?","De la prima treaptă. A2A are sens după ce ești găsit, înțeles și acționabil."),
]

# Șabloane pentru paginile de produs și profil (contextualizate la generare)
GENERIC = [
("Cât costă?","Verificarea inițială este gratuită. Restul se stabilește după ce știm ce lipsește."),
("Cât durează?","Se stabilește după diagnostic, nu înainte. Nu promitem intervale fixe fără să știm ce găsim."),
("Trebuie să-mi refac site-ul?","Nu. Lucrăm peste infrastructura pe care o ai deja."),
("Îmi trebuie cunoștințe tehnice?","Nu. Partea tehnică rămâne la noi."),
("Cu ce începe colaborarea?","Cu verificarea gratuită a firmei tale."),
("Este același lucru cu SEO?","Nu. SEO ține de cum găsesc oamenii pagini. Noi lucrăm la ce înțelege un sistem AI despre firmă."),
("Lucrați și cu firme mici?","Da. Dimensiunea contează mai puțin decât claritatea a ceea ce faci."),
("Ce sisteme AI verificați?","ChatGPT, Gemini, Perplexity și Google AI."),
("Rezultatele sunt garantate?","Garantăm partea pe care o controlăm: infrastructura livrată și măsurarea ei. Selecția făcută de un sistem AI extern nu poate fi garantată de nimeni."),
("Pot renunța oricând?","Da. Nu există obligații după diagnostic."),
("Îmi păstrați datele?","Doar ce este necesar ca să îți răspundem și să livrăm ce ai cerut."),
("Ce se întâmplă dacă nu fac nimic?","Rămâi la nivelul actual. Riscul nu este imediat, ci cumulativ."),
("Cum măsor rezultatul?","Prin rescanare și comparație cu starea inițială."),
("Aveți exemple reale?","Da — ECBTAX este demonstrația publică."),
]
